language: node_js

node_js:
- node

notifications:
    email: true
    slack: webhouseteam:82qu1PX5R5wkYNCW5x6fVlhu

cache:
  directories:
    - node_modules

script: 
    - npm run build
    
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: react-notes-app-client
  #acl: ''
  on:
    repo: cbroberg/notes-app-client
  skip_cleanup: true
  local_dir: build
