language: node_js

node_js:
- node

notifications:
    email: true
    slack: webhouseteam:82qu1PX5R5wkYNCW5x6fVlhu

cache:
  directories:
    - node_modules

script: 
    - brew install awscli
    - yarn deploy
